name: Java CI

on: [push]

jobs:
  build:
    if: github.ref_name != 'main'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit Test Results
          junit_files: |
            plugin/build/test-results/**/*.xml

      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-reports
          path: plugin/build/reports/tests

  publish:
    if: github.ref_name == 'main'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish to Lidalia Repo
        env:
          LIDALIA_MVN_REPO_PASSWORD: ${{ secrets.DEPLOY_PACKAGE_PAT }}
        run: ./gradlew publishPluginMavenPublicationToLidalia-public-maven-repoRepository
